In [8]:
import numpy as np

In [9]:
num_arr = np.array([2,3,23,1])

num_arr

array([ 2,  3, 23,  1])

In [10]:
# Array with 3 integers starting from 0

num_arr_2 = np.arange(3)

num_arr_2

array([0, 1, 2])

In [11]:
# Syntax for arange -> (start, stop, increment)

num_arr_3 = np.arange(1,20, 3)

num_arr_3

array([ 1,  4,  7, 10, 13, 16, 19])

In [12]:
one_arr = np.ones(3)

one_arr

array([1., 1., 1.])

In [13]:
zero_arr = np.zeros(32)

zero_arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
# Arr with random folating numbers between 0 and 1

arr_rand = np.random.rand(3)

arr_rand

array([0.70031443, 0.48121522, 0.13289786])